"""add order archived flag

Revision ID: 0008b2eb8c6c
Revises: 3474cd4841f1
Create Date: 2026-07-13 18:58:00.062579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008b2eb8c6c'
down_revision: Union[str, None] = '3474cd4841f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'orders',
        sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index(op.f('ix_orders_archived'), 'orders', ['archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_archived'), table_name='orders')
    op.drop_column('orders', 'archived')
    # ### end Alembic commands ###
