"""add shipment tracking_registered flag

Revision ID: 1cc82242267c
Revises: dbd6be1e4f2f
Create Date: 2026-07-13 12:57:40.710280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc82242267c'
down_revision: Union[str, None] = 'dbd6be1e4f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: existing rows need a backfill value for
    # this NOT NULL column (autogenerate only emits the Python-side default).
    op.add_column(
        'shipments',
        sa.Column('tracking_registered', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'tracking_registered')
    # ### end Alembic commands ###
